import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NextThemeProvider from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased overflow-x-hidden overflow-y-scroll`}
      >
        <NextThemeProvider>
          <Navbar />
          <main className="px-10 ">{children}</main>
        </NextThemeProvider>
      </body>
    </html>
  );
}
